# Coolify Configuration
services:
  discord-security-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
    volumes:
      - discord_bot_data:/app/data
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Bot is running')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  discord_bot_data: